[project]
name = "lynpy"
version = "0.1.0"
description = "Project to handle LYN Engine files"
authors = [
    {name = "Matias Zommer"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pyrefly>=0.59.1",
    "ruff>=0.15.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["LYN"]


[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "ALL", # Default to all new rules. More maintenance, but more features
]
unfixable = [
    "ERA001", # Commented out code
]
ignore = [
    "COM812", # Conflicts with formatter (trailing comma)
    "D100",   # Missing docstring in public module
    "D101",   # Missing docstring in public class
    "D102",   # Missing docstring in public method
    "D103",   # Missing docstring in public function
    "D104",   # Missing docstring in public package
    "D105",   # Missing docstring in magic method
    "D106",   # Missing docstring in public nested class
    "D107",   # Missing docstring in __init__
    "D203",   # One blank line before class docstring (conflicts with D211)
    "D213",   # Multi-line summary on second line (conflicts with D212)
    "E501",   # Line length (otherwise enforced by formatter)
    "FIX002", # Prevents TODO comments, which are useful
    "ISC001", # Conflicts with formatter
    "TD002",  # Prevents authorless TODO comments, which is annoying
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
